version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: api-inventory-control-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: inventory_user
      MYSQL_PASSWORD: inventory_password
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - estoque-network

networks:
  estoque-network:
    driver: bridge